import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../components/Form";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cep | Sicoob</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cep Sicoob</h1>

        <div className={styles.card}>
          <h2>Insira um cep:</h2>
          <Form />
        </div>
      </main>
    </div>
  );
}
